### ISSUE TITLE
Make a requirements.txt file

### ISSUE THREAD

**Issue by cchaudier** [opensource-expert/ovh-tools#2]
» ./mk_cred.py new
Traceback (most recent call last):
  File "./mk_cred.py", line 19, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

**Comment by Sylvain303** [comment]
small change in the doc and `requirements.txt` added.

**Comment by Sylvain303** [comment]
works form. It was added.
